#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cpprestsdk
Version  : 2.10.6
Release  : 4
URL      : https://github.com/Microsoft/cpprestsdk/archive/v2.10.6.tar.gz
Source0  : https://github.com/Microsoft/cpprestsdk/archive/v2.10.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause MIT Zlib
Requires: cpprestsdk-lib = %{version}-%{release}
Requires: cpprestsdk-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons
BuildRequires : glibc-dev
BuildRequires : openssl-dev
BuildRequires : zlib-dev

%description
## Welcome!
The C++ REST SDK is a Microsoft project for cloud-based client-server communication in native code using a modern asynchronous C++ API design. This project aims to help C++ developers connect to and interact with services.

%package dev
Summary: dev components for the cpprestsdk package.
Group: Development
Requires: cpprestsdk-lib = %{version}-%{release}
Provides: cpprestsdk-devel = %{version}-%{release}

%description dev
dev components for the cpprestsdk package.


%package lib
Summary: lib components for the cpprestsdk package.
Group: Libraries
Requires: cpprestsdk-license = %{version}-%{release}

%description lib
lib components for the cpprestsdk package.


%package license
Summary: license components for the cpprestsdk package.
Group: Default

%description license
license components for the cpprestsdk package.


%prep
%setup -q -n cpprestsdk-2.10.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542692614
mkdir -p clr-build
pushd clr-build
%cmake ../Release
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1542692614
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cpprestsdk
cp Release/tests/common/UnitTestpp/COPYING %{buildroot}/usr/share/package-licenses/cpprestsdk/Release_tests_common_UnitTestpp_COPYING
cp license.txt %{buildroot}/usr/share/package-licenses/cpprestsdk/license.txt
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib/cpprestsdk/cpprestsdk-config.cmake
/usr/lib/cpprestsdk/cpprestsdk-targets-relwithdebinfo.cmake
/usr/lib/cpprestsdk/cpprestsdk-targets.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/cpprest/astreambuf.h
/usr/include/cpprest/asyncrt_utils.h
/usr/include/cpprest/base_uri.h
/usr/include/cpprest/containerstream.h
/usr/include/cpprest/details/SafeInt3.hpp
/usr/include/cpprest/details/basic_types.h
/usr/include/cpprest/details/cpprest_compat.h
/usr/include/cpprest/details/fileio.h
/usr/include/cpprest/details/http_constants.dat
/usr/include/cpprest/details/http_helpers.h
/usr/include/cpprest/details/http_server.h
/usr/include/cpprest/details/http_server_api.h
/usr/include/cpprest/details/nosal.h
/usr/include/cpprest/details/resource.h
/usr/include/cpprest/details/web_utilities.h
/usr/include/cpprest/filestream.h
/usr/include/cpprest/http_client.h
/usr/include/cpprest/http_headers.h
/usr/include/cpprest/http_listener.h
/usr/include/cpprest/http_msg.h
/usr/include/cpprest/interopstream.h
/usr/include/cpprest/json.h
/usr/include/cpprest/oauth1.h
/usr/include/cpprest/oauth2.h
/usr/include/cpprest/producerconsumerstream.h
/usr/include/cpprest/rawptrstream.h
/usr/include/cpprest/streams.h
/usr/include/cpprest/uri.h
/usr/include/cpprest/uri_builder.h
/usr/include/cpprest/version.h
/usr/include/cpprest/ws_client.h
/usr/include/cpprest/ws_msg.h
/usr/include/pplx/pplx.h
/usr/include/pplx/pplxcancellation_token.h
/usr/include/pplx/pplxconv.h
/usr/include/pplx/pplxinterface.h
/usr/include/pplx/pplxlinux.h
/usr/include/pplx/pplxtasks.h
/usr/include/pplx/pplxwin.h
/usr/include/pplx/threadpool.h
/usr/lib64/libcpprest.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcpprest.so.2.10

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cpprestsdk/Release_tests_common_UnitTestpp_COPYING
/usr/share/package-licenses/cpprestsdk/license.txt
